import 'package:vrcma/domain/entities/calendar/enums/calendar_event_platform.dart';
import 'package:vrcma/domain/entities/calendar/enums/group_event_access_type.dart';
import 'package:vrcma/domain/entities/calendar/enums/group_event_category.dart';

/// Interactions with VRChat groups calendar web API.
abstract class IRemoteCalendarRepository {
  Future<bool> verifyCreationPermissions(String userId, String groupId);

  /// Publishes a calendar event returning the unique event ID generated by VRChat.
  Future<String> createEvent({
    required String groupId,
    required String title,
    required DateTime startUtc,
    required DateTime endUtc,
    required String description,
    required GroupEventCategory category,
    required GroupEventAccessType accessType,
    required List<CalendarEventPlatform> platforms,
    required List<String> languages,
    required List<String> tags,
    required bool sendCreationNotification,
    List<String>? roleIds,
    int? hostEarlyJoinMinutes,
    int? guestEarlyJoinMinutes,
    int? closeInstanceAfterEndMinutes,
    bool? usesInstanceOverflow,
  });

  Future<void> deleteEvent(String groupId, String eventId);
}