/// Interactions with VRChat groups calendar web API.
abstract class IRemoteCalendarRepository {
  Future<bool> verifyCreationPermissions(String userId, String groupId);

  /// Publishes a calendar event returning the unique event ID generated by VRChat.
  Future<String> createEvent({
    required String groupId,
    required String title,
    required DateTime startUtc,
    required DateTime endUtc,
    required String description,
    required List<String> platforms,
    required List<String> languages,
    required List<String> tags,
    String? location,
  });

  Future<void> deleteEvent(String groupId, String eventId);
}