// Mocks generated by Mockito 5.4.6 from annotations
// in vrcma/test/domain/usecases/automation/status/coordinate_status_automation_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:vrcma/core/errors/failure.dart' as _i9;
import 'package:vrcma/domain/entities/automation/status_automation.dart' as _i6;
import 'package:vrcma/domain/entities/automation/status_context.dart' as _i11;
import 'package:vrcma/domain/entities/automation/vrc_automation_event.dart'
    as _i8;
import 'package:vrcma/domain/entities/automation/vrc_message.dart' as _i10;
import 'package:vrcma/domain/repositories/i_automation_repository.dart' as _i7;
import 'package:vrcma/domain/repositories/i_status_repository.dart' as _i4;
import 'package:vrcma/domain/usecases/automation/status/evaluate_status_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvaluateStatusResult_1 extends _i1.SmartFake
    implements _i3.EvaluateStatusResult {
  _FakeEvaluateStatusResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IStatusRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIStatusRepository extends _i1.Mock implements _i4.IStatusRepository {
  MockIStatusRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.StatusProfile>> getStatusProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getStatusProfiles, []),
            returnValue: _i5.Future<List<_i6.StatusProfile>>.value(
              <_i6.StatusProfile>[],
            ),
          )
          as _i5.Future<List<_i6.StatusProfile>>);

  @override
  _i5.Future<int> saveStatusProfile(_i6.StatusProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveStatusProfile, [profile]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> deleteStatusProfile(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStatusProfile, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setProfileActive(int? id, bool? isActive) =>
      (super.noSuchMethod(
            Invocation.method(#setProfileActive, [id, isActive]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateLastAppliedStatus(
    int? profileId,
    _i6.StatusType? status,
    String? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastAppliedStatus, [
              profileId,
              status,
              message,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [IAutomationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAutomationRepository extends _i1.Mock
    implements _i7.IAutomationRepository {
  MockIAutomationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i8.VrcAutomationEvent> watchAutomationEvents() =>
      (super.noSuchMethod(
            Invocation.method(#watchAutomationEvents, []),
            returnValue: _i5.Stream<_i8.VrcAutomationEvent>.empty(),
          )
          as _i5.Stream<_i8.VrcAutomationEvent>);

  @override
  _i5.Future<void> acceptRequestInvitation(
    _i8.RequestInviteEvent? requestInvite,
    int? slot,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptRequestInvitation, [requestInvite, slot]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> acceptInvitation(_i8.InviteReceivedEvent? invite) =>
      (super.noSuchMethod(
            Invocation.method(#acceptInvitation, [invite]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> acceptFriendRequest(
    _i8.FriendRequestReceivedEvent? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptFriendRequest, [request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> rejectNotificationWithMessage(
    _i8.IncomingUserEvent? notification,
    int? slot,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rejectNotificationWithMessage, [
              notification,
              slot,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dismissNotification(_i8.IncomingUserEvent? notification) =>
      (super.noSuchMethod(
            Invocation.method(#dismissNotification, [notification]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Either<_i9.Failure, void>> updateVrcMessageSlot({
    required String? userId,
    required String? messageType,
    required int? slot,
    required String? content,
    required _i10.VrcMessageType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateVrcMessageSlot, [], {
              #userId: userId,
              #messageType: messageType,
              #slot: slot,
              #content: content,
              #type: type,
            }),
            returnValue: _i5.Future<_i2.Either<_i9.Failure, void>>.value(
              _FakeEither_0<_i9.Failure, void>(
                this,
                Invocation.method(#updateVrcMessageSlot, [], {
                  #userId: userId,
                  #messageType: messageType,
                  #slot: slot,
                  #content: content,
                  #type: type,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i9.Failure, void>>);

  @override
  _i5.Future<List<_i10.VrcRemoteMessage>> getRemoteVrcMessages(
    String? userId,
    _i10.VrcMessageType? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRemoteVrcMessages, [userId, type]),
            returnValue: _i5.Future<List<_i10.VrcRemoteMessage>>.value(
              <_i10.VrcRemoteMessage>[],
            ),
          )
          as _i5.Future<List<_i10.VrcRemoteMessage>>);

  @override
  _i5.Future<_i2.Either<_i9.Failure, void>> updateRemoteStatus({
    required _i6.StatusType? status,
    required String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRemoteStatus, [], {
              #status: status,
              #description: description,
            }),
            returnValue: _i5.Future<_i2.Either<_i9.Failure, void>>.value(
              _FakeEither_0<_i9.Failure, void>(
                this,
                Invocation.method(#updateRemoteStatus, [], {
                  #status: status,
                  #description: description,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i9.Failure, void>>);
}

/// A class which mocks [EvaluateStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvaluateStatusUseCase extends _i1.Mock
    implements _i3.EvaluateStatusUseCase {
  MockEvaluateStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.EvaluateStatusResult> execute({
    required _i6.StatusProfile? profile,
    required _i11.StatusContext? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #profile: profile,
              #context: context,
            }),
            returnValue: _i5.Future<_i3.EvaluateStatusResult>.value(
              _FakeEvaluateStatusResult_1(
                this,
                Invocation.method(#execute, [], {
                  #profile: profile,
                  #context: context,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.EvaluateStatusResult>);
}
